apiVersion: apps/v1
kind: Deployment
metadata:
    name: "meetingservice"
spec:
    replicas: 3
    selector:
        matchLabels:
            app: my-app
    template:
        metadata:
            labels:
                app: my-app
        spec:
            containers:
                - name: my-container
                  image: tsfn14g99.azurecr.io/meetingservice:v1.1
                  ports:
                      - containerPort: 8082
